/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/albums': RouteRecordInfo<
      '/albums',
      '/albums',
      Record<never, never>,
      Record<never, never>,
      | '/albums/'
      | '/albums/[id]'
      | '/albums/create'
      | '/albums/my'
    >,
    '/albums/': RouteRecordInfo<
      '/albums/',
      '/albums',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/albums/[id]': RouteRecordInfo<
      '/albums/[id]',
      '/albums/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/albums/create': RouteRecordInfo<
      '/albums/create',
      '/albums/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/albums/my': RouteRecordInfo<
      '/albums/my',
      '/albums/my',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/playlists/': RouteRecordInfo<
      '/playlists/',
      '/playlists',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/playlists/[id]': RouteRecordInfo<
      '/playlists/[id]',
      '/playlists/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/playlists/my': RouteRecordInfo<
      '/playlists/my',
      '/playlists/my',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/register': RouteRecordInfo<
      '/register',
      '/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/songs/': RouteRecordInfo<
      '/songs/',
      '/songs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/songs/[id]': RouteRecordInfo<
      '/songs/[id]',
      '/songs/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/songs/my': RouteRecordInfo<
      '/songs/my',
      '/songs/my',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/songs/upload': RouteRecordInfo<
      '/songs/upload',
      '/songs/upload',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/albums.vue': {
      routes:
        | '/albums'
        | '/albums/'
        | '/albums/[id]'
        | '/albums/create'
        | '/albums/my'
      views:
        | 'default'
    }
    'src/pages/albums/index.vue': {
      routes:
        | '/albums/'
      views:
        | never
    }
    'src/pages/albums/[id].vue': {
      routes:
        | '/albums/[id]'
      views:
        | never
    }
    'src/pages/albums/create.vue': {
      routes:
        | '/albums/create'
      views:
        | never
    }
    'src/pages/albums/my.vue': {
      routes:
        | '/albums/my'
      views:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
    }
    'src/pages/playlists/index.vue': {
      routes:
        | '/playlists/'
      views:
        | never
    }
    'src/pages/playlists/[id].vue': {
      routes:
        | '/playlists/[id]'
      views:
        | never
    }
    'src/pages/playlists/my.vue': {
      routes:
        | '/playlists/my'
      views:
        | never
    }
    'src/pages/register.vue': {
      routes:
        | '/register'
      views:
        | never
    }
    'src/pages/songs/index.vue': {
      routes:
        | '/songs/'
      views:
        | never
    }
    'src/pages/songs/[id].vue': {
      routes:
        | '/songs/[id]'
      views:
        | never
    }
    'src/pages/songs/my.vue': {
      routes:
        | '/songs/my'
      views:
        | never
    }
    'src/pages/songs/upload.vue': {
      routes:
        | '/songs/upload'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
